name: NuGet
on:
  push:
    branches:
      - master
      - dev
      - dev-1.35.0
      - dev-1.35.0-ReStructured

jobs:
  nuget-1:
    name: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Pack
        run: |
          dotnet pack -c Release --output nupkgs BeatTogether.MasterServer.Interface/BeatTogether.MasterServer.Interface.csproj
      - name: Publish
        run: |
          dotnet nuget push "nupkgs/BeatTogether.MasterServer.*.nupkg" -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate

  nuget-2:
    name: https://api.nuget.org/v3/index.json
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      - name: Pack
        run: |
          dotnet pack -c Release --output nupkgs BeatTogether.MasterServer.Interface/BeatTogether.MasterServer.Interface.csproj
      - name: Publish
        run: |
          dotnet nuget push "nupkgs/BeatTogether.MasterServer.*.nupkg" -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
